export const movies = [
    {
        id: '1',
        trailerLink: 'https://www.youtube.com/embed/p9EiQQ912TQ?si=4UaImtEXpf9kGAL_',
        title: 'SHE MUST OBEY',
        description: "She Must Obey is a Nigerian movie directed by Funke Akindele. It follows the story of a woman facing societal pressures and expectations regarding marriage while navigating personal and professional challenges",
        posterURL: 'https://guardian.ng/wp-content/uploads/2023/10/GL_1ST_OCTOBER_2023-1-scaled.jpg',
        rating: 7.8,
    },
    {
        id: '2',
        trailerLink: 'https://www.youtube.com/embed/pEUZVfeCU94?si=gFCVcLR2SGUdFo_B',
        title: 'A TRIBE CALLED JUDAH',
        description: "A Tribe Called Judah is a documentary that delves into the cultural heritage, traditions, and contemporary identity of the Judah tribe. Through interviews and archival footage, the film highlights their history, struggles, and resilience, showcasing their contributions to society from ancestral roots to present-day challenges and achievements.",
        posterURL: 'https://xplorenollywood.com/wp-content/uploads/2023/12/A-tribe-called-Judah-.jpg',
        rating: 7.9,
    },
    {
        id: '3',
        trailerLink: 'https://www.youtube.com/embed/NJIrscmh2NQ?si=PNhcywyLHSk3WmLY',
        title: 'ORISA',
        description: 'Orisa is a Nigerian drama film that delves into the complexities of traditional African spirituality and modern-day challenges. Set against the backdrop of a rural Nigerian community, it follows the journey of a young woman who must navigate the expectations of her family and the demands of her faith. As she grapples with personal dilemmas and societal pressures, she discovers the power of self-discovery and the importance of cultural heritage.',
        posterURL: 'https://media.premiumtimesng.com/wp-content/files/2023/08/image2-1.jpeg',
        rating: 5.1,
    },
    {
        id: '4',
        trailerLink: 'https://www.youtube.com/embed/QuGnwMj8Bu0?si=lOIieozrAVQlM0N7',
        title: 'BIG LOVE',
        descriptiption:"Big Love is a Nigerian romantic drama film that explores love, betrayal, and forgiveness in the context of a complex family dynamic. It delves into the intricacies of relationships and societal expectations, offering a compelling narrative set against the backdrop of Nigerian culture.",
        posterURL: 'https://m.media-amazon.com/images/M/MV5BZGNkNjgzZDgtNTJiMS00MTJmLWI2ODAtOGFmOGJjYTFmYWQ5XkEyXkFqcGdeQXVyNzc5NDg5Mjc@._V1_.jpg',
        rating: 7.8,
    },
    {
        id: '5',
        trailerLink: 'https://www.youtube.com/embed/AsaMWxppznk?si=jgVgxja5qU-mL-NG',
        title: 'MR&MRS SMITH',
        description: "Rampage is a thrilling action film where genetic experiments go awry, causing three animals to mutate into colossal and aggressive monsters. As chaos ensues, a primatologist and a team must stop the destruction of the city",
        posterURL: 'https://i.guim.co.uk/img/media/6917f95e13963ea6bef300347c3c2bbf73d37325/5_182_2985_1791/master/2985.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=0011ab0e7a6b0cd2d9ff15996056dab6',
        rating: 8.5,
    },
    {
        id: '6',
        trailerLink: 'https://www.youtube.com/embed/Gp2Mydl330s?si=XDh2-9CwyBqhUaMs',
        title: 'SUPER NATURAL',
        description: '"Supernatural" is a long-running TV series that follows two brothers, Sam and Dean Winchester, as they hunt demons, ghosts, monsters, and other supernatural beings across America while uncovering family secrets and battling their own personal demons..',
        posterURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7wIJJsaqade7zqeqhMySCSDg1_O1R_gQUfjqfypnvnwjSgwCEtPC2G0uOyN4Uualf3xk&usqp=CAU',
        rating: 8.1,
    },
    {
        id: '7',
        trailerLink: 'https://www.youtube.com/embed/dgRYWeEyaYE?si=TacC2b5tjhJU9gb5',
        title: 'BREATH OF LIFE',
        description: 'Breath of Life is a Nigerian movie that tells the story of a young womans journey to overcome adversity and find hope amidst societal challenges and personal struggles.',
        posterURL: 'https://i.pinimg.com/originals/ad/37/8f/ad378fa6b8df316c6668ac6f4e091a98.jpg',
        rating: 8.2,
    },
    {
        id: '8',
        trailerLink: 'https://www.youtube.com/embed/iM7MFXbjy8k?si=UZlQjPPsqMyvhxY6',
        title: 'RICHES',
        description: " Riches is a compelling TV series that chronicles the lives of a wealthy family navigating the complexities of power, love, betrayal, and ambition. Set against the backdrop of opulence and luxury, the show delves into the intricacies of family dynamics and the lengths individuals will go to protect their fortunes and legacies." ,    
        posterURL: 'https://i.guim.co.uk/img/media/32cce9bb09c3680726ac878dc174f7508dcb7552/0_299_6204_3723/master/6204.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=cebbaf2e3b92d9683c4fcdfd32a115d8 ',
        rating: 7.5,
    },
    {
        id: '9',
        trailerLink: 'https://www.youtube.com/embed/OLSWVCwy88g?si=6WTqqvbHvuO0JJYT',
        title: 'HAZBIN HOTEL',
        description:  "Hazbin Hotel is an animated film that follows the chaotic adventures of Charlie, the princess of Hell, as she attempts to rehabilitate demons by giving them a chance at redemption in her hotel. Filled with dark humor, vibrant animation, and memorable characters, the movie explores themes of redemption, acceptance, and the complexities of morality in the afterlife.",
        posterURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs0cm84pnaosBmk-9DHNbofCxlQJbftBFI9hqoG5ihNw&s',
        rating: 5.1,
    },
    {
        id: '10',
        trailerLink: 'https://www.youtube.com/embed/42HhowRmTSE?si=4yriGYreCyi7jsGh',
        title: 'BROTHERHOOD',
        description: "Brotherhood Nigeria is a captivating film that follows the lives of two brothers, navigating their way through the challenges of brotherhood, loyalty, and ambition in Nigeria. Set against the backdrop of societal pressures and familial expectations, the movie delves into themes of love, betrayal, and the pursuit of success in a rapidly changing society",
        posterURL: 'https://www.bellanaija.com/wp-content/uploads/2022/07/Brotherhood-Movie-PostersIMG_2046.jpg',
        rating: 8.5,
    },
    {
        id: '11',
        trailerLink: 'https://www.youtube.com/embed/GSycMV-_Csw?si=g96_wmlJNvRMV5ha',
        title: 'REACHER',
        description:'Reacher is an action-packed film centered around the enigmatic Jack Reacher, a former military police officer who travels the country solving crimes and dispensing justice. Filled with thrilling fight sequences, intricate mysteries, and compelling characters, the movie follows Reacher as he unravels complex conspiracies and faces formidable adversaries, all while staying one step ahead of danger. ',
        posterURL: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.guim.co.uk%2Fimg%2Fmedia%2F2773fc537e8c68e7c6a33f84290d97728be4cbe4%2F0_260_3900_2340%2Fmaster%2F3900.jpg%3Fwidth%3D1200%26height%3D1200%26quality%3D85%26auto%3Dformat%26fit%3Dcrop%26s%3D92aadc2e2c3a8c56771233e7f97fc9dc&tbnid=CylLySgytmfftM&vet=12ahUKEwic7IvC45mEAxXzTKQEHShKDgUQMygEegQIARBW..i&imgrefurl=https%3A%2F%2Fwww.theguardian.com%2Ftv-and-radio%2F2022%2Ffeb%2F04%2Freacher-review-lee-child-jack-reacher-adaptation-amazon-prime-video&docid=27iDNSlZCaR5cM&w=1200&h=1200&q=guardian%20reacher%20movie%20poster&ved=2ahUKEwic7IvC45mEAxXzTKQEHShKDgUQMygEegQIARBW',
        rating: 6.9,
    },
    {
        id: '12',
        trailerLink: 'https://www.youtube.com/embed/eoOaKN4qCKw',
        title: 'FAST X',
        description: 'Fast X is an action-packed adrenaline rush with high-speed car chases, intense heists, and an all-star cast, taking the Fast & Furious franchise to new heights.',
        posterURL: 'https://cdn.cinematerial.com/p/297x/3edzwhfn/fast-x-movie-poster-md.jpg?v=1678807508',
        rating: 6.9,
    },
    {
        id: '13',
        trailerLink: 'https://www.youtube.com/embed/1Q8fG0TtVAY',
        title: 'WONDER WOMAN',
        description: "Wonder Woman is a thrilling superhero film featuring Diana, an Amazonian warrior princess, discovering her true powers to stop a global war, showcasing bravery, compassion, and empowerment in the process.",
        posterURL: 'https://cdn.cinematerial.com/p/297x/qr1ws2xg/wonder-woman-movie-poster-md.jpg?v=1523893366',
        rating: 7.9,
    },
    {
        id: '14',
        trailerLink: 'https://www.youtube.com/embed/IBh9c2WFFz0',
        title: 'MISSION KANDAHAR',
        description: "Mission Kandahar is a gripping war drama following a team of soldiers on a perilous mission in Afghanistan. Facing relentless enemies and internal struggles, they strive to complete their mission and survive.",
        posterURL: 'https://cdn.cinematerial.com/p/297x/bujepjj3/kandahar-movie-poster-md.jpg?v=1683659196',
        rating: 7.1,
    },
    {
        id: '15',
        trailerLink: 'https://www.youtube.com/embed/itnqEauWQZM',
        title: 'TRANSFORMERS: RISE OF THE BEAST',
        description: "Transformers: Rise of the Beast is an action-packed sci-fi film where Autobots and Decepticons battle on Earth. The story unveils ancient Transformer history and introduces new transforming creatures amidst epic clashes.",
        posterURL: 'https://flxt.tmsimg.com/assets/p20201199_v_v13_am.jpg',
        rating: 6.5,
    },
    {
        id: '16',
        trailerLink: 'https://www.youtube.com/embed/Y5zqweZAEKI',
        title: 'PUSS IN BOOTS 2',
        description: "Puss in Boots 2 is an animated adventure film where the swashbuckling cat Puss teams up with Humpty Dumpty and Kitty Softpaws to stop the villainous Jack and Jill from unleashing evil forces.",
        posterURL: 'https://cdn.cinematerial.com/p/297x/zayj6zx3/puss-in-boots-the-last-wish-movie-poster-md.jpg?v=1655305563',
        rating: 7.1,
    },
    {
        id: '17',
        trailerLink: 'https://www.youtube.com/embed/BmllggGO4pM',
        title: 'THE GRAY MAN',
        description: "The Gray Man is an action thriller film based on the novel series. It follows a former CIA operative turned assassin as he evades enemies while protecting his family. Directed by Anthony and Joe Russo, starring Ryan Gosling and Chris Evans.",
        posterURL: 'https://cdn.cinematerial.com/p/297x/pfgv4tnc/the-gray-man-movie-poster-md.jpg?v=1653403863',
        rating: 8.2,
    },
    {
        id: '18',
        trailerLink: 'https://www.youtube.com/embed/_Z3QKkl1WyM',
        title: 'BLACK PANTHER 2',
        description: "Black Panther 2 continues the Marvel superhero saga after the demise of T'Challa. It explores Wakanda's new leadership and confronts challenges, including a mysterious threat that puts the nation at risk.",
        posterURL: 'https://m.media-amazon.com/images/I/71nDLLIubWL.AC_SL1100.jpg',
        rating: 8.1,
    },
    {
        id: '19',
        trailerLink: 'https://www.youtube.com/embed/uYPbbksJxIg',
        title: 'OPPENHEIMER',
        description: "Oppenheimer is a biographical drama film directed by Christopher Nolan, depicting the life of J. Robert Oppenheimer, the physicist and key figure behind the development of the atomic bomb during World War II.",
        posterURL: 'https://cdn.cinematerial.com/p/297x/2afqhdxx/oppenheimer-movie-poster-md.jpg?v=1683305737',
        rating: 8.1,
    },
    {
        id: '20',
        trailerLink: 'https://www.youtube.com/embed/d9MyW72ELq0',
        title: 'AVATAR: THE WAY OF WATER',
        description: "Avatar: The Way of Water is the anticipated sequel to Avatar, directed by James Cameron. It continues the story on Pandora, exploring new underwater realms and the Na'vi's connection with nature.",
        posterURL: 'https://cdn.cinematerial.com/p/297x/ayniyqcx/avatar-the-way-of-water-movie-poster-md.jpg?v=1667461543',
        rating: 8.2,
    },
]